services:
  t3-chat-discord-bot:
    build: .
    container_name: t3-chat-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data:rw
    networks:
      - t3-chat-network

networks:
  t3-chat-network:
    driver: bridge 